// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storage

import (
	"database/sql"
	"time"
)

type Block struct {
	ID            sql.NullString `json:"id"`
	MessageID     string         `json:"message_id"`
	BlockType     string         `json:"block_type"`
	ModalityType  int64          `json:"modality_type"`
	MimeType      string         `json:"mime_type"`
	Content       string         `json:"content"`
	SequenceOrder int64          `json:"sequence_order"`
	CreatedAt     time.Time      `json:"created_at"`
}

type Message struct {
	ID              string         `json:"id"`
	ParentID        sql.NullString `json:"parent_id"`
	Title           sql.NullString `json:"title"`
	Role            string         `json:"role"`
	ToolResultError bool           `json:"tool_result_error"`
	CreatedAt       time.Time      `json:"created_at"`
}
