// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storage

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Block queries
	CreateBlock(ctx context.Context, arg CreateBlockParams) error
	// queries.sql
	// Message queries
	CreateMessage(ctx context.Context, arg CreateMessageParams) error
	DeleteBlock(ctx context.Context, id string) error
	DeleteMessage(ctx context.Context, id string) error
	GetBlock(ctx context.Context, id string) (Block, error)
	GetBlocksByMessage(ctx context.Context, messageID string) ([]Block, error)
	GetChildrenCount(ctx context.Context, parentID sql.NullString) (int64, error)
	// Dialog Reconstruction
	GetDialogPath(ctx context.Context, id string) ([]GetDialogPathRow, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetMostRecentMessage(ctx context.Context) (Message, error)
	HasChildren(ctx context.Context, parentID sql.NullString) (int64, error)
	ListMessages(ctx context.Context) ([]Message, error)
	ListMessagesByParent(ctx context.Context, parentID sql.NullString) ([]Message, error)
}

var _ Querier = (*Queries)(nil)
