/*
Package sqlcgen contains SQL query bindings generated by sqlc for the storage
package's SQLite implementation.

This package is intentionally low-level and mirrors schema.sql/queries.sql. The
storage package wraps these generated types and queries with higher-level dialog
semantics and public interfaces.
*/
package sqlcgen
