// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"time"
)

type AcpSession struct {
	ID            string         `json:"id"`
	LastMessageID sql.NullString `json:"last_message_id"`
	Cwd           string         `json:"cwd"`
	Title         string         `json:"title"`
	ModelRef      string         `json:"model_ref"`
	ThinkingLevel string         `json:"thinking_level"`
	CostUsd       float64        `json:"cost_usd"`
	CreatedAt     time.Time      `json:"created_at"`
}

type Block struct {
	ID            sql.NullString `json:"id"`
	MessageID     string         `json:"message_id"`
	BlockType     string         `json:"block_type"`
	ModalityType  int64          `json:"modality_type"`
	MimeType      string         `json:"mime_type"`
	Content       string         `json:"content"`
	ExtraFields   sql.NullString `json:"extra_fields"`
	SequenceOrder int64          `json:"sequence_order"`
	CreatedAt     time.Time      `json:"created_at"`
}

type Message struct {
	ID                 string         `json:"id"`
	ParentID           sql.NullString `json:"parent_id"`
	CompactionParentID sql.NullString `json:"compaction_parent_id"`
	Role               string         `json:"role"`
	ToolResultError    bool           `json:"tool_result_error"`
	MessageExtraFields sql.NullString `json:"message_extra_fields"`
	ModelRef           sql.NullString `json:"model_ref"`
	ModelID            sql.NullString `json:"model_id"`
	ModelType          sql.NullString `json:"model_type"`
	ModelDisplayName   sql.NullString `json:"model_display_name"`
	InputTokens        sql.NullInt64  `json:"input_tokens"`
	OutputTokens       sql.NullInt64  `json:"output_tokens"`
	CacheReadTokens    sql.NullInt64  `json:"cache_read_tokens"`
	CacheWriteTokens   sql.NullInt64  `json:"cache_write_tokens"`
	CreatedAt          time.Time      `json:"created_at"`
}
