// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type Conversation struct {
	ID           string         `json:"id"`
	ParentID     sql.NullString `json:"parent_id"`
	UserMessage  string         `json:"user_message"`
	ExecutorData []byte         `json:"executor_data"`
	CreatedAt    time.Time      `json:"created_at"`
	Model        string         `json:"model"`
}
