// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateConversation(ctx context.Context, arg CreateConversationParams) error
	DeleteConversation(ctx context.Context, id string) error
	GetChildConversations(ctx context.Context, id string) ([]string, error)
	// queries.sql
	GetConversation(ctx context.Context, id string) (Conversation, error)
	GetLatestConversation(ctx context.Context) (Conversation, error)
	ListConversations(ctx context.Context) ([]ListConversationsRow, error)
}

var _ Querier = (*Queries)(nil)
