name: Execute CPE on Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  cpe-process:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install CPE
        run: go install github.com/spachava753/cpe@latest

      - name: Cache CPE conversation
        uses: actions/cache@v3
        with:
          path: .cpeconvo
          key: cpe-cache-${{ github.event.pull_request.head.ref }}

      - name: Run CPE
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          CPE_CLAUDE_3_5_SONNET_URL: ${{ secrets.CPE_CLAUDE_3_5_SONNET_URL }}
        run: |
          # Combine PR title and body for input
          echo "${{ github.event.pull_request.title }}" > pr_input.txt
          echo "" >> pr_input.txt
          echo "${{ github.event.pull_request.body }}" >> pr_input.txt
          
          # Run CPE with the input
          cat pr_input.txt | cpe

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Check if there are any changes to commit
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "CPE: Process PR #${{ github.event.pull_request.number }}"
            git push
          else
            echo "No changes to commit"
          fi